on:
  push:
    branches:
      - main

jobs:
  GitlabMirror:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://code.swecha.org/pacchu/pacgobot"
      env:
        FORCE_PUSH: "true"
        GITLAB_HOSTNAME: "code.swecha.org"
        GITLAB_USERNAME: "pacchu"
        GITLAB_PASSWORD: ${{ secrets.SWECHA_GITHUB_TOKEN }}
        GITLAB_PROJECT_ID: "13579"
        GITHUB_TOKEN: ${{ secrets.SWECHA_GITHUB_TOKEN }}
