on:
  push:
    branches:
      - master

jobs:
  GitlabMirror:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://code.swecha.org/pacchu/pacgobot"
      env:
        FORCE_PUSH: "true"
        GITLAB_HOSTNAME: "gitlab.com"
        GITLAB_USERNAME: "itspacchu"
        GITLAB_PASSWORD: ${{ secrets.SWECHA_GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: "42900035"
        GITHUB_TOKEN: ${{ secrets.SWECHA_GITHUB_TOKEN }}
